.github/workflows/gradle.yml

- [Github Actions CI: 자동 빌드 및 테스트 하기](https://bcp0109.tistory.com/362)

ci: Github Actions Gradle CI 추가

---

src/main/java/com/tm/gogo/domain/FavoriteTrail.java
src/main/java/com/tm/gogo/domain/HikingLog.java
src/main/java/com/tm/gogo/domain/Location.java
src/main/java/com/tm/gogo/domain/Member.java
src/main/java/com/tm/gogo/domain/Mountain.java
src/main/java/com/tm/gogo/domain/MountainImage.java
src/main/java/com/tm/gogo/domain/Notice.java
src/main/java/com/tm/gogo/domain/RecommendTrail.java
src/main/java/com/tm/gogo/domain/Terms.java
src/main/java/com/tm/gogo/domain/Trail.java
src/main/java/com/tm/gogo/domain/TrailDetail.java
src/main/java/com/tm/gogo/domain/Youtube.java

도메인 추가
ERD: https://app.diagrams.net/#G12ZNh6gccYzUH0fn_0Q5_QLevcRoN14ek

feature : domain

---

src/main/java/com/tm/gogo/domain/BaseEntity.java
src/main/java/com/tm/gogo/domain/FavoriteTrail.java
src/main/java/com/tm/gogo/domain/HikingLog.java
src/main/java/com/tm/gogo/domain/Location.java
src/main/java/com/tm/gogo/domain/Member.java
src/main/java/com/tm/gogo/domain/Mountain.java
src/main/java/com/tm/gogo/domain/MountainImage.java
src/main/java/com/tm/gogo/domain/Notice.java
src/main/java/com/tm/gogo/domain/RecommendTrail.java
src/main/java/com/tm/gogo/domain/Terms.java
src/main/java/com/tm/gogo/domain/Trail.java
src/main/java/com/tm/gogo/domain/TrailDetail.java
src/main/java/com/tm/gogo/domain/Youtube.java

- `createdAt`, `updatedAt` 추가
- 생성날짜, 수정날짜 적용

feat: BaseEntity 추가

---

src/main/java/com/tm/gogo/web/response/ErrorCode.java
src/main/java/com/tm/gogo/web/response/ErrorDto.java
src/main/java/com/tm/gogo/web/response/GlobalExceptionHandler.java
src/main/java/com/tm/gogo/web/response/ResponseDto.java

feat: #4 Response, Error 포맷 추가

---

build.gradle
src/main/java/com/tm/gogo/config/SecurityConfig.java
src/main/java/com/tm/gogo/config/SwaggerConfig.java
src/main/java/com/tm/gogo/web/auth/AuthController.java
src/main/java/com/tm/gogo/web/member/MemberController.java

- #3 
API 문서 제공 및 테스트를 위한 Swagger 추가입니다
Swagger 와 중첩 DTO 를 같이 쓰면 이슈가 있어서 수정해야겠네요
http://localhost:8080/swagger-ui.html 로 접속 가능합니다

feat: #3 Swagger 추가

---

src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailQueryRepository.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailDto.java

refactor: #40 등산로 리스트 내려줄 때 필요한 데이터 추가

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLogQueryRepository.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogController.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogDto.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogResponse.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailController.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

- #28 
-HikingLog 조회 기능 추가
memberId 로 최신순인 HikingLog를 조회합니다.

feat: #28 HikingLog 조회 기능 추가

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLogQueryRepository.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogDto.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

- #28 
- HikingLogDto에 등산로 이름 추가
등산로그 리스트에 기획과 달리 등산로 이름이 누락되어 추가했습니다.

fix: #28 HikingLogDto 등산로 이름 추가

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLog.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogImage.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailService.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogController.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogDetailResponse.java
src/main/java/com/tm/gogo/web/response/ErrorCode.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

feature: #28 등산 로그 하나 조회 기능 추가

---

src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailQueryRepository.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailCondition.java
src/test/java/com/tm/gogo/service/HikingTrailServiceTest.java

feat: #48 등산로 조회할 때 등산로명으로 필터링 하는 기능 추가

---

src/main/java/com/tm/gogo/domain/favorite_trail/FavoriteTrailRepository.java
src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailService.java
src/main/java/com/tm/gogo/helper/SecurityUtil.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailController.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailDto.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailsResponse.java
src/main/java/com/tm/gogo/web/response/GlobalExceptionHandler.java
src/test/java/com/tm/gogo/service/HikingTrailServiceTest.java
src/test/resources/application.yml

- #49
- 등산로 리스트를 내려줄 때 즐겨찾기 여부도 같이 내려감
- 로그인 상태인 경우 해당 유저 기준으로 즐겨찾기 여부
- 로그인된 사용자가 아닌 경우에는 전부 `false` 로 내려줌
아래와 같은 화면이며 비로그인 상태에서 즐겨찾기 버튼을 누를 경우 로그인 안내가 나올 예정

feat: #49 등산로 조회 시 즐겨찾기 여부 표시 (로그인 여부로 분기)

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/helper/ImageUploadService.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogController.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogRequest.java
src/main/java/com/tm/gogo/web/response/ErrorCode.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

- #52
- imageFile 을 받아서 바로 등록
- Test 코드는 일단 제거

feat: #52 HIkingLog 등록할 때 이미지 파일을 업로드

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/helper/ImageUploadService.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogController.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogRequest.java
src/main/java/com/tm/gogo/web/response/ErrorCode.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

Reverts GoGo-tm/GoGo_Server#53

Revert "feat: #52 HIkingLog 등록할 때 이미지 파일을 업로드"

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLog.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/domain/member/Member.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogController.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

feat: #28 등산기록 하나 수정하기 추가

---

src/main/java/com/tm/gogo/domain/hiking_log/HikingLogImageMap.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogQueryRepository.java
src/main/java/com/tm/gogo/domain/hiking_log/HikingLogService.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogDto.java
src/main/java/com/tm/gogo/web/hiking_log/HikingLogResponse.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

- #58
- HikingLogDto 리스트 반환에 List<String> imageUrls 추가하였습니다.

feat: #58 반환값에 이미지 추가

---

src/main/java/com/tm/gogo/web/hiking_log/HikingLogDetailResponse.java
src/test/java/com/tm/gogo/service/HikingLogServiceTest.java

- #61
- 반환값 추가
등산로 이름 추가 했습니다.

feat: #61 등산로그 하나 조회 반환값 추가

---

src/main/java/com/tm/gogo/config/SecurityConfig.java

- #69 
- https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter 참고해서 적용

config: #69 Spring Security deprecated 대응

---

src/main/java/com/tm/gogo/domain/Notice.java
src/main/java/com/tm/gogo/domain/notice/NoticeQueryRepository.java
src/main/java/com/tm/gogo/domain/notice/NoticeRepository.java
src/main/java/com/tm/gogo/domain/notice/NoticeService.java
src/main/java/com/tm/gogo/web/notice/NoticeController.java
src/main/java/com/tm/gogo/web/notice/NoticeDto.java
src/main/java/com/tm/gogo/web/notice/NoticesResponse.java
src/test/java/com/tm/gogo/service/NoticeServiceTest.java

- #71
- 공지사항이라 실제 데이터는 많지 않겠지만 미래를 고려해 무한 스크롤 구조로 만들었습니다

feat: #71 공지사항 조회 API 추가

---

src/main/java/com/tm/gogo/config/SecurityConfig.java

config: #71 공지사항 조회 API 권한 설정 (모두 허용)

---

src/main/java/com/tm/gogo/web/favorite_trail/FavoriteTrailController.java

- #37 
- 등산로 즐겨찾기 관련 API Swagger 설명이 빠져있어서 추가

docs: #37 등산로 즐겨찾기 API Swagger 추가

---

src/main/java/com/tm/gogo/domain/notice/Notice.java
src/main/java/com/tm/gogo/domain/notice/NoticeQueryRepository.java
src/main/java/com/tm/gogo/domain/notice/NoticeRepository.java
src/test/java/com/tm/gogo/service/NoticeServiceTest.java
src/test/java/com/tm/gogo/service/YoutubeServiceTest.java

- #71
- Notice Entity 개발하면서 패키지 이동 안했던게 확인되어 수정함

style: #71 Notice Entity 패키지 이동

---

src/main/java/com/tm/gogo/config/SecurityConfig.java
src/main/java/com/tm/gogo/domain/favorite_trail/FavoriteTrailService.java
src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailService.java
src/main/java/com/tm/gogo/domain/recommend_trail/RecommendTrail.java
src/main/java/com/tm/gogo/domain/recommend_trail/RecommendTrailRepository.java
src/main/java/com/tm/gogo/domain/recommend_trail/RecommendTrailService.java
src/main/java/com/tm/gogo/domain/recommend_trail/RecommendTrailTheme.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailDto.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailsResponse.java
src/main/java/com/tm/gogo/web/recommend_trail/RecommendTrailController.java
src/main/java/com/tm/gogo/web/recommend_trail/RecommendTrailResponse.java
src/test/java/com/tm/gogo/service/RecommendTrailServiceTest.java

- #73
- 추천 등산로 API 개발
- 등산로 즐겨찾기 판단하는 로직 리팩토링

feat: #73 추천 등산로 조회 API 개발

---

src/main/java/com/tm/gogo/domain/oauth/OauthApiClient.java
src/main/java/com/tm/gogo/domain/oauth/kakao/KakaoApiClient.java
src/main/java/com/tm/gogo/domain/oauth/kakao/KakaoOauthService.java
src/main/java/com/tm/gogo/domain/oauth/naver/NaverApiClient.java
src/main/java/com/tm/gogo/domain/oauth/naver/NaverMyInfo.java
src/main/java/com/tm/gogo/domain/oauth/naver/NaverOauthService.java
src/main/java/com/tm/gogo/domain/oauth/naver/NaverToken.java
src/main/java/com/tm/gogo/web/oauth/KakaoLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/NaverLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/OauthController.java
src/main/java/com/tm/gogo/web/oauth/OauthLoginRequest.java
src/main/resources/application-oauth.yml
src/test/java/com/tm/gogo/service/KaKaoOauthServiceTest.java
src/test/resources/application.yml

feat: #22 Naver Oauth 로그인 추가

---

src/main/java/com/tm/gogo/domain/oauth/google/GoogleApiClient.java
src/main/java/com/tm/gogo/domain/oauth/google/GoogleMyInfo.java
src/main/java/com/tm/gogo/domain/oauth/google/GoogleOauthService.java
src/main/java/com/tm/gogo/domain/oauth/google/GoogleToken.java
src/main/java/com/tm/gogo/web/oauth/GoogleLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/OauthController.java
src/main/resources/application-oauth.yml
src/test/resources/application.yml

feat: Google OAuth 로그인 추가

---

src/main/java/com/tm/gogo/domain/oauth/OauthApiClient.java
src/main/java/com/tm/gogo/domain/oauth/OauthService.java
src/main/java/com/tm/gogo/domain/oauth/RequestOauthService.java
src/main/java/com/tm/gogo/domain/oauth/google/GoogleApiClient.java
src/main/java/com/tm/gogo/domain/oauth/kakao/KakaoApiClient.java
src/main/java/com/tm/gogo/domain/oauth/naver/NaverApiClient.java
src/main/java/com/tm/gogo/web/oauth/GoogleLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/KakaoLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/NaverLoginRequest.java
src/main/java/com/tm/gogo/web/oauth/OauthController.java
src/main/java/com/tm/gogo/web/oauth/OauthLoginRequest.java
src/test/java/com/tm/gogo/service/KaKaoOauthServiceTest.java

- #22
- Naver, Kakao, Google 서비스 간에 의존성 제거

refactor: #22 Oauth 도메인 의존성 제거

---

src/main/java/com/tm/gogo/interceptor/InterceptorConfig.java
src/main/java/com/tm/gogo/interceptor/LoggingInterceptor.java

- #84
- Spring Interceptor 로 로그 기능 추가

feat: #84 API 요청, 응답 로그 추가

---

src/main/java/com/tm/gogo/config/SecurityConfig.java

- #85 
- CORS 설정이 필요해서 추가
Spring Security 를 사용하는 경우 Spring WebMVC 설정이 아닌 Security 설정을 추가해야 함
Spring WebMVC 설정을 추가해도 Security 를 먼저 타서 소용없음

config: #85 Spring Security CORS 설정 추가

---

src/main/java/com/tm/gogo/domain/member/CommandMemberService.java
src/main/java/com/tm/gogo/domain/member/QueryMemberService.java

feat: #90 Member 캐시 삭제

---

build.gradle
src/main/java/com/tm/gogo/GogoApplication.java
src/main/java/com/tm/gogo/config/CacheConfig.java
src/main/java/com/tm/gogo/config/RedisConfig.java
src/main/java/com/tm/gogo/domain/hiking_trail/HikingTrailService.java
src/main/java/com/tm/gogo/parameter/Scrollable.java
src/main/java/com/tm/gogo/web/hiking_trail/HikingTrailCondition.java
src/test/resources/application.yml

feat: #95 HikingTrail 조회 캐시 적용
